/*
 * generated by Xtext 2.40.0
 */
package org.xtext.example.mydsl;

import com.google.inject.Binder;
import com.google.inject.Singleton;
import org.eclipse.xtext.common.types.util.TypeReferences;
import org.eclipse.xtext.xbase.XbaseRuntimeModule;
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer;
import org.xtext.example.mydsl.types.MyDslTypeComputer;
import org.xtext.example.mydsl.types.MyDslTypeReferences;

public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {

//	@Override
	public Class<? extends TypeReferences> bindTypeReferences() {
	    return org.xtext.example.mydsl.types.MyDslTypeReferences.class;
	}
}
